include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/di/injectable.config.dart # там приватные импорты ему не нравятся
    - "**/*.freezed.dart"

linter:
  rules:
    prefer_relative_imports: true
    directives_ordering: true
    prefer_const_constructors: true

