arb-dir: lib/l10n
template-arb-file: app_ru.arb
output-localization-file: app_localizations.dart
untranslated-messages-file: lib/l10n/untranslated_messages.txt
output-dir: lib/l10n/generated
synthetic-package: false
