name: dnd5_character_creator
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  gin_app_runner:
    path: plugins/gin_app_runner
  cupertino_icons: ^1.0.4
  injectable: ^1.5.3
  easy_localization: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
