name: dnd5_character_creator
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  gin_app_runner:
    path: plugins/gin_app_runner
  gin_app_logger:
    path: plugins/gin_app_logger
  cupertino_icons: ^1.0.4
  injectable: ^1.5.3
  easy_localization: ^3.0.1
  get_it: ^7.2.0
  flutter_bloc: ^8.0.1
  dio: ^4.0.6
  json_serializable: ^6.2.0
  json_annotation: ^4.5.0

dev_dependencies:
  freezed: ^2.0.3+1
  injectable_generator: ^1.5.3
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
